name: Release
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        use_efi: ['true', 'false']
    steps:
      - uses: actions/checkout@v2
      # PREPARE BUILDX
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders
      # BUILD WITH BUILDX
        - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build.Dockerfile
          push: false
          tags: local/temp:latest
          output: type=local,dest=output
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            output/rootfs.tar.gz

